version: '2'
services:
    mongo:
      image: mongo:3
      volumes:
        - "mongo-data:/data/db"
    elasticsearch:
      image: "elasticsearch:2"
      command: "elasticsearch -Des.cluster.name='graylog'"
      volumes:
        - "es-data:/usr/share/elasticsearch/data"
    graylog:
      image: graylog2/server:latest
      volumes:
        - "graylog-data:/usr/share/graylog/data/journal"
        - ./graylog/config:/usr/share/graylog/data/config
        - ./tls/syslog:/etc/tls
      environment:
        GRAYLOG_PASSWORD_SECRET: randomsalt
        GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
        GRAYLOG_REST_TRANSPORT_URI: http://${EXTERNAL_IP}:12900
      depends_on:
        - mongo
        - elasticsearch
      ports:
        - "9001:9000"
        - "12900:12900"
        - "12201/tcp:12201/tcp"
        - "1514/tcp:1514/tcp"

volumes:
    mongo-data:
        driver: local
    es-data:
        driver: local
    graylog-data:
        driver: local
