version: '2'
services:
    mongo:
      image: "mongo:3"
      volumes:
        - "mongo-data:/data/db"
    elasticsearch:
      image: "elasticsearch:2"
      command: "elasticsearch -Des.cluster.name='graylog'"
      volumes:
        - "es-data:/usr/share/elasticsearch/data"
    graylog:
      image: graylog2/server
      command: -d
      volumes:
        - "graylog-data:/usr/share/graylog/data/journal"
        - ./graylog/config:/usr/share/graylog/data/config
        - ./tls/syslog:/usr/share/graylog/data/syslog
      environment:
        GRAYLOG_PASSWORD_SECRET: randomsalt
        GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
        GRAYLOG_REST_TRANSPORT_URI: http://192.168.1.199:12900
      depends_on:
        - mongo
        - elasticsearch
      ports:
        - "9000:9000"
        - "12900:12900"
        - "12201/tcp:12201/tcp"
        - "1514/tcp:1514/tcp"
    app:
      #image: ehazlett/docker-demo:latest
      image: nginx:latest
      logging:
        driver: syslog
        options:
          syslog-address: "tcp://192.168.1.199:1514"
          syslog-address: "tcp+tls://192.168.1.199:1514"
          #syslog-tls-ca-cert: "/Users/ahromis/workspace/docker-demo/tls/syslog/ca.pem"
          syslog-tls-cert: "/Users/ahromis/workspace/docker-demo/tls/syslog/cert.pem"
          syslog-tls-key: "/Users/ahromis/workspace/docker-demo/tls/syslog/key.pem"
          syslog-tls-skip-verify: "true"
          tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
      ports:
        - 8080:80

volumes:
    mongo-data:
        driver: local
    es-data:
        driver: local
    graylog-data:
        driver: local
