version: "2"

services:
    interlock:
        image: ehazlett/interlock:master
        command: run -c /etc/interlock/config.toml
        ports:
            - 8080
        volumes:
            - ./config.toml:/etc/interlock/config.toml
            - /var/run/docker.sock:/var/run/docker.sock
    
    nginx:
        image: nginx:latest
        entrypoint: nginx
        command: -g "daemon off;" -c /etc/nginx/nginx.conf
        ports:
            - 80:80
            - 443:443
        labels:
            - "interlock.ext.name=nginx"
        #links:
        #    - interlock:interlock
        depends_on:
            - interlock
        volumes:
            - ./ssl:/etc/nginx/ssl
    
    app:
        image: ehazlett/docker-demo:latest
        ports:
            - 8080
        labels:
            - "interlock.ssl=true"
            - "interlock.ssl_only=true"
            - "interlock.ssl_cert=/etc/nginx/ssl/cert.pem"
            - "interlock.ssl_cert_key=/etc/nginx/ssl/key.pem"
            - "interlock.port=8080"
            - "interlock.hostname=test"
            - "interlock.domain=demo"
        depends_on:
            - nginx
