version: '2'
services:
    mongo:
      image: "mongo:3"
      volumes:
        - "mongo-data:/data/db"
    elasticsearch:
      image: "elasticsearch:2"
      command: "elasticsearch -Des.cluster.name='graylog'"
      volumes:
        - "es-data:/usr/share/elasticsearch/data"
    graylog:
      image: graylog2/server
      volumes:
        - "graylog-data:/usr/share/graylog/data/journal"
        - ./config:/usr/share/graylog/data/config
      environment:
        GRAYLOG_PASSWORD_SECRET: saltnpeppa
        GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
        GRAYLOG_REST_TRANSPORT_URI: http://127.0.0.1:12900
      depends_on:
        - mongo
        - elasticsearch
      labels:
        - "interlock.hostname=graylog"
        - "interlock.domain=dev.localhost"
        - "interlock.ssl=true"
        - "interlock.ssl_only=true"
        - "interlock.ssl_cert=/etc/nginx/ssl/cert.pem"
        - "interlock.ssl_key=/etc/nginx/ssl/key.pem"
        - "interlock.port=9000"
      ports:
        - "9000:9000"
        - "12900:12900"
        - "12201/udp:12201/udp"
        - "1514/udp:1514/udp"



volumes:
    mongo-data:
        driver: local
    es-data:
        driver: local
    graylog-data:
        driver: local
